### ISSUE TITLE
Populate repo

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-model-gb#1]
Analogous with https://github.com/riboseinc/csd , this will contain doc model. May instead end up containing rendering code.

**Comment by opoudjis** [comment]
GB standards basically use the ISO Directives 2

But the GB standards have different types, GB, GBT, GBZ and DB and Guide
Terms are also localized strings (contains Chinese and English)
Title is Chinese and English (3 parts)
And then it’s just formatting

**Comment by opoudjis** [comment]
@ronaldtse , the grammar you describe is simply isostandard with the following changes; please confirm:

````
default namespace = "http://riboseinc.com/gbstandard"
  
start = gb-standard

language = element language { ( "zh" | "en" ) }

script = element script { ( "Hans" | "Latn" ) }

# identical structure to iso-standard
gb-standard =
  element gb-standard {
    title+,
    status,
    creator,
    language,
    script,
    type,
    id,
    version?,
    copyright,
    sections
  }

type =
  element type {
     ( "GB" | "GBT" | "GBZ" | "DB" | "Guide" )
  }

preferred =
  element preferred { localisedstring+ }

admitted =
  element admitted { localisedstring+ }

deprecates =
  element deprecates { localisedstring+ }

localisedstring =
  element string {
    attribute language { ( "zh" | "en" ) },
    TextElement+
}
````

I'm generating the inherited grammar in https://github.com/riboseinc/isodoc-models, as I've been doing consistently.

**Comment by ronaldtse** [comment]
Let me add — there is also a “publishing date” and an “active date”. Maybe I should update the GBBibItem model? Or is that a general standard document thing?

The GBDocTypes have been updated in the model.

**Comment by ronaldtse** [comment]
Now Type is a complex thing...

**Comment by opoudjis** [comment]
The grammars don't differentiate doc model and bib item, they're all in the one file. The biblio model already has a publishing date; you'd need to add an active date. So:

````
BibliographicItem =
     attribute id { xsd:ID },
     attribute type { "article" | "book" | "booklet" | "conference" | "manual" |
                      "proceedings" | "presentation" | "thesis" | "techreport" |
                      "standard" | "unpublished" }?,
    (bname | formatted), source?, publishdate, docidentifier*, accesseddate?, activedate?, creator*,
    publisher*, edition?,
    biblionote*, partof*, creationdate?, language*, script*, abstract?

activedate = element activedate { xsd:date }

````

Where have you put the GBDocTypes?

**Comment by ronaldtse** [comment]
You can see them on the front page README.

**Comment by opoudjis** [comment]
Work new types into grammar.
