### ISSUE TITLE
Not all standards have Technical Committee

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-model-gb#10]
@opoudjis Looks like Social standards don't have Technical Committee. But in GbBibliographicItem model TC is required. Suggest accepting an organization instead of a TC in that case.

**Comment by opoudjis** [comment]
@ronaldtse is this true? 

The social group organisation is already in place as the issuer; it would be an utter confusion of the model to cast the social group as the TC as well. Instead, we should make the TC optional if this is so, with it required for National, Local, Sector standards, and omitted (presumably) for enterprise and social groups.

**Comment by ronaldtse** [comment]
Yes, this is unfortunately true. A National standard must be backed by a TC, but other GB-related standards may be backed by other organizations.

* Enterprise standards: any company / organization
* Social standard: a Social Organization
* Local standards: one or more local government departments
* Sector standards: the standards-setting organization(s) we have in the prefix map (https://github.com/riboseinc/gbdoc/blob/master/models/gb-standard-sector-prefix.adoc)

**Comment by opoudjis** [comment]
Made tech committee optional
