### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [metanorma/metanorma-model-gb#11]
Convert Metanorma GbDoc StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.

- [PNG.zip](https://github.com/riboseinc/metanorma-model-gb/files/2339088/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-gb/files/2339089/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-gb/files/2339090/SVG.zip)

**Comment by ronaldtse** [comment]
Integrated in b4bf9450a5d475729fe72ee44f3f23b643c450d3. Thanks @VasBu !
