### ISSUE TITLE
Explanation of Chinese standard front page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-gb#4]
Let's me answer the front page stuff (use the GM/T 0009 document as an example). (bracket numbers are changable)

1. numbers on the top left corner - these are Chinese library categorization numbers. "ICS [35.040] " (international categorization number), "L [80]", (some kind of category), “备案号: [38307-2013]" (categorized as ID)

2. top right corner - "GM" means "cryptographic standard". 

3. top title - "PRC Cryptographic Industry Standard" (see gbdoc HTML output). This changes per type of standard.

4. right hand side below top title - "GM/T 0009-2012". Again, GM for "Cryptographic". "/T" for "recommended" ("mandatory standards" omit the "/T"). "0009" is project number just like ISO's. "-2012" is edition, note that it differs from ISO's ":2012"

5. Center title, first Chinese, then English

6. Bottom left date: Publishing date. Bottom right date: Date this standard becomes active.

7. Center bottom: the publisher ("publishing organization") of this standard. See GBDoc model for the full list.

**Comment by opoudjis** [comment]
1. Are these static and applicable to all GB specs? If not, we will need to include them in the GB document model.

2, 3: If we're doing a family of GB-like specs and not just GB specs, I will need a lookup table of top titles and logos for the different flavours of standard as well—or rather, you will need different front page templates for each flavour. Right now I'm only doing GB.

4, 5. Already done.

6. Done.

7. Is an image right now.

**Comment by ronaldtse** [comment]
1. Yes. Except the “library categorization numbers”, all the elements described are in the GBDoc model. 

2. And 3. Yes it’s a family of Standards. All text elements are included in the GBDoc repo (the adoc files in models/). Only the “GB” graphical element is in GBDoc (or asciidoctor-gb), I will get the rest prepared when I can. 

Thanks!
