### ISSUE TITLE
Local standard example

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-gb#5]
These are the samples:

https://github.com/riboseinc/gbdoc/blob/master/reference-docs/DB%2011:366-2006.pdf
https://github.com/riboseinc/gbdoc/blob/master/reference-docs/DB%2013:T%201092-2009.pdf
https://github.com/riboseinc/gbdoc/blob/master/reference-docs/DB%2044:1989-2017.pdf

"DB 11:366-2006" means:
* DB => local standard
* 11 => location ID: Beijing City (https://github.com/riboseinc/gbdoc/blob/master/models/gb-standard-local-prefix.adoc)
* 366 => document ID
* 2006 => edition

**Comment by opoudjis** [comment]
So DB is ambiguous with seismology as a sector. That's regrettable.

**Comment by opoudjis** [comment]
What is the standard agency for these local standards? the Beijing one and the Guangdong one look nothing alike.

**Comment by ronaldtse** [comment]
Yes, DB is ambiguous and in use for both.

Seismology standards:
http://www.cea.gov.cn/manage/html/8a8587881632fa5c0116674a018300cf/bzjldzhybj/index.html

**Comment by ronaldtse** [comment]
The Beijing one is from 2006 and I suspect isn't following GB/T 1.1 yet. The Guangdong and Hebei ones look similar.

**Comment by ronaldtse** [comment]
It also seems like the publisher of local standards may differ per standard. All of them have a local standard publisher (i.e., official province publisher), but some standards have an additional government department publisher.

**Comment by opoudjis** [comment]
Could I please have the Chinese for "{PROVINCE} Official Standard Publisher"? We can leave out the additional government publisher in the template, surely.

**Comment by ronaldtse** [comment]
“{PROVINCE}质量技术检测局”

“河北省质量技术检测局” Hebei Province Quality Technology Testing Bureau
“广东省质量技术检测局” Guangdong Province Quality Technology Testing Bureau
“北京市质量技术检测局” Beijing City Quality Technology Testing Bureau

**Comment by opoudjis** [comment]
OK. I'm good.

**Comment by ronaldtse** [comment]
@opoudjis BTW DB and DBXX don't actually conflict -- DB is just for seismology, while DBXX is for local standards (XX must be provided).
