### ISSUE TITLE
Update model according to official data structure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-gb#6]
See example here: https://github.com/riboseinc/gbbib/issues/1

**Comment by ronaldtse** [comment]
@opoudjis could you have do it and also update asciidoctor-gb? There might be some details to move back from asciidoctor-gb to here... Thanks!

**Comment by opoudjis** [comment]
Are CCS and the L identifier the same thing?

**Comment by ronaldtse** [comment]
CCS is "Chinese Categorization Scheme", a Chinese library categorization number.

I actually just found the full schema for what GbBib should support.

This is the bibliographic information for GB/T 5795-2006, the "Chinese Categorization Scheme".

Attributes:

* StandardNumber 标准编号：GB/T 5795-2006
* StandardTitle in Chinese 标准名称：中国标准书号
* StandardTitle in English 英文名称：China Standard Book Number
* StandardState 标准状态：Current 现行
* IndustryCategory 行业分类：GB
* StandardSort 标准类别： 基础
* ICS 国际标准分类号： 01.140.20
* CCS 中国标准分类号： A14
* PlanNumber 计划单号：20061584-T-469
* NumberOfPages 页数：18
* Abstract 标准简介：本标准规定了中国标准书号的结构、显示方式及印刷位置、分配及使用规则、与中国标准书号有关的数据以及中国标准书号的管理系统。 本标准为在中国依法设立的出版者所出版或制作的每一专题出版物及其每一版本提供唯一确定的和国际通用的标识编码方法。

Doc relations:
* ReplacedStandard 代替国标号： GB/T 5795-1986,GB/T 5795-2002,GB/T 5795-2002
* ReplacedByStandard 被代替国标号 :
* AdoptedInternationalStandard:
  * AdoptedInternationalStandard 采用国际标准： ISO
  * AdoptedInternationalStandardNo 采用国际标准号： ISO 2108:2005
  * AdoptedInternationalStandardName 采标名称： 信息与文献 国际标准书号
  * ApplicationDegree 采用程度： MOD

Dates:
* RevocatoryDate 废止时间：
IssuanceDate 发布日期：2006-10-18
ExecuteDate 实施日期：2007-01-01
FirstIssuanceDate 首发日期：1986-01-16
PublicationDate 出版日期：2007-01-01
ReviewAffirmanceDate 复审确认日期 ：

Entities:

* Issuers 发布部门：中华人民共和国国家质量监督检验检疫总局, 中国国家标准化管理委员会
* Proposer 提出单位：新闻出版总置条码中心
* TechnicalCommittees 归口单位：全国信息与文献标准化技术委员会
* Governor 主管部门：国家标准化管理委员会
* DraftingCommittee 起草单位：新闻出版总置条码中心
* DraftingAuthors 起草人：齐相潼、蔡京生、邢瑞华、傅祚华、孔德龙
* Publisher 出版社：中国标准出版社

**Comment by ronaldtse** [comment]
@opoudjis could you help update the GbBib model to accept the above items? Thanks!

**Comment by opoudjis** [comment]
That doesn't answer my question of whether L and CCS are distinct; I'll assume they are...

**Comment by ronaldtse** [comment]
CCS is the categorization standard. See https://github.com/riboseinc/cn-ccs-codes.

"L" is the level 1 categorization, the number after is the level 2.

**Comment by opoudjis** [comment]
**Need vocabulary (English and Chinese) for Standard Status**: [StandardState 标准状态：Current 现行]. In the schema it will just be `bibdata/status`, there's no substages presumably like in ISO. 

**Need vocabulary (English and Chinese) for Standard Category** [StandardSort 标准类别： 基础]. I presume this will slot into `bibdata@type`.

**Will add Plan Number as an optional library identifier, alongside CCS.**

ReplacedStandard is `docrelations/@type = obsoletes`

ReplacedByStandard is `docrelations/@type = updatedBy`. (**I've changed it from "updates", which sounds identical to "obsoletes".**)

AdoptedInternationalStandard is `docrelation/@type = derivedFrom`, although we're modelling it instead as `docrelation/@type = equivalent, nonequivent, identical`

RevocatoryDate 废止时间：is `bibdata/date/@type = obsoleted`
IssuanceDate 发布日期：is `bibdata/date/@type = created`
ExecuteDate 实施日期：is `bibdata/date/@type = activated`
FirstIssuanceDate 首发日期：is **bibdata/date/@type = first_created (which I'm adding to vocabulary)**
PublicationDate 出版日期：is `bibdata/date/@type = published`
ReviewAffirmanceDate 复审确认日期 ：is **bibdata/date/@type = reviewed (which I'm adding to vocabulary)**

Issuer 发布部门: is `contributor[@type = 'publisher']`
Proposer 提出单位：is `contributor[role = 'proposer']`
TechnicalCommittees 归口单位：is `bibdata/gbcommittee[@type = 'technical']`
Governor 主管部门：`contributor[role = 'governing authority']` (or `'sponsor'`)
DraftingCommittee 起草单位：`bibdata/gbcommittee[@type = 'drafting']` **which I'm adding to model; I am also allowing there to be more than one gbcommittee. Please confirm provisional and drafting are not the same thing**
DraftingAuthors 起草人：is `contributor[@type = 'author']`
Publisher 出版社：is `contributor[@type = 'publisher']`

**Comment by opoudjis** [comment]
Now needs to address https://github.com/riboseinc/gbdoc/pull/7

**Comment by ronaldtse** [comment]
@opoudjis 

> Need vocabulary (English and Chinese) for Standard Status:

Given in #7.

> Need vocabulary (English and Chinese) for Standard Category [StandardSort 标准类别： 基础]. I presume this will slot into bibdata@type.

Given in #7.

> Will add Plan Number as an optional library identifier, alongside CCS.

Done in #7, Plan number is an attribute now.

> IssuanceDate 发布日期：is bibdata/date/@type = created
> FirstIssuanceDate 首发日期：is bibdata/date/@type = first_created (which I'm adding to vocabulary)

Why don't we use "created" for "FirstIssuance" and "issued" for "Issuance"?

> ReviewAffirmanceDate 复审确认日期 ：is bibdata/date/@type = reviewed (which I'm adding to vocabulary)

Can we call this the "affirm" date since it is "reviewed and affirmed" (i.e. no updates are necessary to this document?

-----------


So the contributing roles are very confusing -- these are all separate roles (as you can see above, it is of the same document).

How about we do this:

> Issuer 发布部门: is contributor[type = 'publisher']

So, the issuer, as you see in the provided example, is separate from the publisher. It is the "issuer" who sends the document to the printing press (the "publisher") that "publishes" it. Maybe we just call it the "issuer"?

> Proposer 提出单位：is contributor[role = 'proposer']

Agree.

> TechnicalCommittees 归口单位：is bibdata/gbcommittee[type = 'technical']

Agree. Sounds like it can be more than one from their schema ("TechnicalCommittees").

> Governor 主管部门：contributor[role = 'governing authority'] (or 'sponsor')

Maybe we call it the "Authority" (`contributor[role = 'authority']`)?

> DraftingCommittee 起草单位

These are actually the "Drafting Organizations", the organizations that the DraftingAuthors belong to. So maybe it's best to put them as "contributor[type = 'author']" too

> DraftingAuthors 起草人：is contributor[type = 'author']

Agree.

> Publisher 出版社：is contributor[type = 'publisher']

Agree.

**Comment by opoudjis** [comment]
I dislike issuance as a counterpart to publishing, and would rather call what the printing press does "printed". But I see that Google shows there is a lot of usage of "issues a standard". When it comes to electronic distribution of standards, is it the issuing authority that puts them up on their website, or the "printing" authority? If the former, I'd call them the publisher still. If the latter, I'd call them the publisher. If there's no electronic publication at all, I'd still call them printers as opposed to publishers.

Is issuance and first issuance not about initial version vs current version? But even if it is, created vs issued (or published) still holds. Is there a real distinction between date of issuance and date of publication though?

"affirmed" is not idiomatic; "vetted" is, even if it was originally slang; and so is "approved".

The issuing authority is really the corporate author, as opposed to the individual author. But you do seem to need both separate. (Especially if we make drafting organisations be actual content creators/authors.) Again: is the authority/sponsor really distinct from the Issuer? That seems unnecessarily complicated.

**Comment by ronaldtse** [comment]
@opoudjis not trying to be pedantic but unfortunately this is really how the data is organized.

Issuers 发布部门：中华人民共和国国家质量监督检验检疫总局, 中国国家标准化管理委员会
Proposer 提出单位：新闻出版总置条码中心
TechnicalCommittees 归口单位：全国信息与文献标准化技术委员会
Governor 主管部门：国家标准化管理委员会
DraftingCommittee 起草单位：新闻出版总置条码中心
DraftingAuthors 起草人：齐相潼、蔡京生、邢瑞华、傅祚华、孔德龙
Publisher 出版社：中国标准出版社

"First Issuance" is the date of issuance of the first edition.

The "issuing authority" is the one who approves the standard.

The "publisher" is the organization that distributes (electronically and on paper). The publisher in this case is the one who also owns the copyright.

The "affirmed" date is the ISO "confirmed" date. Maybe we should call it "confirmed" instead. e.g.,. https://www.iso.org/standard/50655.html

All this information is provided as a combination of these two sources:
* http://www.std.gov.cn/gb/search/gbDetailed?id=5DDA8BA07AC218DEE05397BE0A0A95A7
* http://www.sac.gov.cn/was5/web/search?channelid=97779&templet=gjcxjg_detail.jsp&searchword=STANDARD_CODE=%27GB/T%2024276-2017%27

**Comment by opoudjis** [comment]
CCS:

They are much simpler than the grammar says.

In A42, A is the field, 4 is the group, and 2 is the subgroup. The CCS code is A42, not (as the grammar implies) A, A40/49, 42.

The group has an artificial name E00/09, which simply means the range from E00 to E09. But in practice, there is no need at all to break this down into field, group, and subgroup in the xml: it's just a single code, and something else (like your new gem) should be breaking it down into its three components.

I propose that CSS *not* be broken down in the XML.

**Comment by opoudjis** [comment]
GB standard type: for consistency with ISOdoc, these are hyphenated.

There is no Standard Type in the ISO grammar. There is the Document Type, but that divides standards into specifications, reports, guide, etc; this Standard Type is rather a thematic classification, and it is not the same kind of thing, nor should it inherit from the ISO Standard Type.

You now dangerously have a GbStandardType container and a GbStandardType element. I am renaming the latter GBTopic, and making it an element of GbStandardType.

**Comment by opoudjis** [comment]
From what I gather, Standard State is inferred from the bibliographic dates in the XML, so I don't need to add anything.

The bibliographic dates were originally: "published" | "accessed" | "created" | "activated" | "obsoleted" . The dates as worded here still look very idiosyncratic, and they should be as generic as possible:

I propose:

"accessed": date that document was last accessed
"created": date that first version of the document was created (FirstIssuanceDate 首发日期)
"activated": date that this version of the document came into effect  (ExecuteDate 实施日期)
"obsoleted": date that this version of the document became no longer in effect  (RevocatoryDate 废止时间)
"confirmed": date that this version was approved by its issuing authority (ReviewAffirmanceDate 复审确认日期)
"updated": date that current version of the document was created [in this case is redundant with "issued"; but I can see standards bodies preferring updated rather than issued. I do too.]
"issued": date that current version of the document was issued, i.e. authorised for publication by the issuing authority (IssuanceDate 发布日期)
"published": date that current version of the document was published (i.e. distributed for use) (PublicationDate 出版日期)

If you're ok with these, these need to go to bib-models. So do the definitions.

**Comment by opoudjis** [comment]
Issuer 发布部门: is contributor[@type = 'issuer']
Publisher 出版社：is contributor[@type = 'publisher']
Proposer 提出单位：is contributor[@type = 'proposer']
TechnicalCommittees 归口单位：is bibdata/gbcommittee[@type = 'technical']
Governor 主管部门：contributor[@type = 'authority'] 
DraftingCommittee 起草单位：bibdata/gbcommittee[@type = 'author'][organization]
DraftingAuthors 起草人：is contributor[@type = 'author'][person]

**Comment by opoudjis** [comment]
The Issuer is inferred by isodoc from the prefix, so I see no reason to add it to the XML.

**Comment by opoudjis** [comment]
I've put definitions of all of these into the README.

**Comment by opoudjis** [comment]
@ronaldtse Please confirm before I close the ticket.

**Comment by ronaldtse** [comment]
I almost forgot — I was told that the issuer can change with the same prefix. The example given was an environmental standard.

So it’s easier if we allow the user to manually override all these names. 

Also, DraftingCommittee should just be contributor[author], just like DraftingAuthor. These are usually the organizations that participated in the authoring process, its not actually a committee.

**Comment by ronaldtse** [comment]
Looking at the list I almost want to say that TechnicalCommittee should also be represented as a “contributor”. Please flame me :wink:

**Comment by opoudjis** [comment]
I've put in Technical Committee as a contributor, copied across from gbcommittee.

I need the drafting committee to be a separate document attribute in the document header than author, to differentiate person authors from organisation authors. But they both have the author role.

**Comment by opoudjis** [comment]
Done
