### ISSUE TITLE
GbStandardSocialPrefix length

### ISSUE THREAD

**Issue by andrew2net** [metanorma/metanorma-model-gb#9]
@ronaldtse @opoudjis the GbStandardSocialPrefix length determined as 3 characters, but on site http://www.ttbz.org.cn I found from 3 to 6 chars.

**Comment by ronaldtse** [comment]
Yes we should relax the constraints. The standard designates three characters (for the new ones) but old prefixes stay hard.

**Comment by opoudjis** [comment]
@andrew2net : again, please assign me any tickets you want me to address; I have too much of a backlog to respond promptly to notifications.

Constraint relaxed. I am not relaxing the Enterprise prefix unless I'm told to.

**Comment by ronaldtse** [comment]
The Enterprise prefix (in the model) already allows any number of characters. So it's fine.
